FROM golang as build
ENV GO111MODULE=on
WORKDIR /app
COPY . .
RUN go build -ldflags "-X main.build=34" -a -tags netgo -o /bin/drone-docker ./cmd/drone-docker

FROM docker:18.06-dind
COPY --from=build /bin/drone-docker /bin/
ENTRYPOINT ["/usr/local/bin/dockerd-entrypoint.sh", "/bin/drone-docker"]
